application: bookie-bookish-new
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /images
  static_dir: images
- url: /stylesheet
  static_dir: stylesheet
- url: /javascript
  static_dir: javascript
- url: /.*
  script: bookiebookish.application


